version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - "grafana-storage:/var/lib/grafana"
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=fitbit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    hostname: pgadmin4
    environment:
      - PGADMIN_SETUP_EMAIL=admin@admin.com
      - PGADMIN_SETUP_PASSWORD=admin
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - "pdAdmin-data:/var/lib/pgadmin"
volumes:
  grafana-storage:
  dbdata:
  pdAdmin-data: